
echo "Setting up MINDSW-1.0"

WORKDIR=$PWD
INSTALL_DIR=$PWD/install


export PATH=$INSTALL_DIR/bin:$PATH
export LD_LIBRARY_PATH=$INSTALL_DIR/lib:$LD_LIBRARY_PATH
export LIBRARY_PATH=$INSTALL_DIR/lib:$LIBRARY_PATH
export C_INCLUDE_PATH=$INSTALL_DIR/include:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=$INSTALL_DIR/include:$C_INCLUDE_PATH
